version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: postgres_prod
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    image: ${BACKEND_TAG}
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    container_name: frontend_prod
    env_file: .env
    image: ${FRONTEND_TAG}
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    container_name: nginx_prod
    image: ${GATEWAY_TAG}
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
